# fly.toml app configuration file generated for hahahub on 2023-09-19T12:23:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hahahub"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]